### ISSUE TITLE
PNG file is not found

### ISSUE THREAD

**Issue by bionoir** [lao-tseu-is-alive/lausanne-map-wmts-mn95-leaflet#1]
https://github.com/lao-tseu-is-alive/lausanne-map-wmts-mn95-leaflet/blob/29f654a2a8610c845ef085ee3fd277b42ae5fcc4/main.js#L28

Hello, I'm trying to implemente Leaflet with tiles coming from https://tilesmn95.lausanne.ch/tiles/1.0.0/fonds_geo_osm_bdcad_couleur/default/2021/, but I only receives errors since the ".png" files cannot be found.
GET https://tilesmn95.lausanne.ch/tiles/1.0.0/fonds_geo_osm_bdcad_couleur/default/2021/swissgrid_05/7/66/45.png     404

Moreover, if I use your code, I cannot instanciate objects:
jquery-3.5.1.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'CRS')
    at HTMLDocument.<anonymous> (my_script.js:16:28)
    at e (jquery-3.5.1.min.js:2:30005)
    at t (jquery-3.5.1.min.js:2:30307)
  
My projects includes the libraries:
leaflet-src.esm.js
leaflet-src.js
leaflet.js

Thanks

**Comment by lao-tseu-is-alive** [comment]
From your message I thing you are not buiding the code with vitejs ?
can you confirm please ?
did you try with the usual workflow ?

by "usual" workflow, i mean to use the above commands in your shell:

1. git clone https://github.com/lao-tseu-is-alive/lausanne-map-wmts-mn95-leaflet.git
2. cd lausanne-map-wmts-mn95-leaflet/
3. npm i
4. npm run dev

then navigate with your browser to http://localhost:5173/

**Comment by bionoir** [comment]
Hello, thank you for the quick reply!

Unfortunately, I'm not using the "usual" workflow and implementing the JS part in a "classic" Python/Django application.
Maybe my issue is not pertinent with the your projetct scope.
Thank you anyways.

**Comment by lao-tseu-is-alive** [comment]
Ok well I did prepare a codepen 
For you to experiment :
https://codepen.io/lao-tseu-is-alive/pen/eYPYRPM

I hope with this you can better figure out what is not working with your code

If you still have trouble
maybe be you can send me some example code ?

**Comment by lao-tseu-is-alive** [comment]
I am closing this issue because it is not related directly to the code in this repository
