### ISSUE TITLE
Using along with swisstopo wmts swissimage

### ISSUE THREAD

**Issue by lperozzi** [lao-tseu-is-alive/lausanne-map-wmts-mn95-leaflet#2]
I would like to use `https://tilesmn95.lausanne.ch/tiles/1.0.0/fonds_geo_osm_bdcad_couleur/default/2021/swissgrid_05/{z}/{y}/{x}.png` along with the swisstop swissimages WMTS `https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/2056/{z}/{x}/{y}.jpeg`, but since the different resolution and axis inversion i have some difficulties to integrate them together. Have you some hints on how to takle the problem?

**Comment by lao-tseu-is-alive** [comment]
Hello Mr Perozzi,

It's great to see your interest in combining Lausanne Tiles with other WMTS sources, such as Swisstop Swissimages, in your projects. However, this query doesn't constitute an issue for this specific GitHub project, which focuses on integrating Lausanne WMTS tiles with Leaflet.

We do work on integrating various WMTS sources in different interactive map projects, primarily with OpenLayers. If you'd like to contribute to the community, I encourage you to explore and implement a solution yourself. Once you have some working code, consider submitting a pull request or sharing your implementation through other channels.

Thanks for your engagement, and I wish you success in your endeavors."
